#!/usr/bin/bash

# Cores
VERDE='\033[32m'
ROXO='\033[38;5;57m'
FIM='\033[0m'

# Banner
echo -e "${VERDE}"'        ______
 _   _ (____  \  _   _
( \ / )| |   | || | | |
 ) X ( | |__/ / | |_| |
(_/ \_)|_____/   \__  |
 by: rodricbr   (____/'"${FIM}"

# Número da contagem de rodadas do dado
echo ""
read -rp "$(echo -e "$VERDE"" Dices: ""$FIM")" DADO
read -rp "$(echo -e "$VERDE"" Range: ""$FIM")" ALCANCE
#FIM=5

# Se o output do dado e do alcance forem alfabéticos (não forem números)...
if [[ "$DADO" =~ ^[[:alpha:]]$ && "$ALCANCE" =~ ^[[:alpha:]]$ ]]; then
  echo -e "Only numbers are valid!"
  exit 1
else
  :
fi

# Iniciando contador
INDEX=0
for ((i = 1; i <= DADO; i++)); do
  (( "INDEX+=1" )) || :; printf "${ROXO}[$INDEX]${FIM} ${VERDE}Number:${FIM} %s\n" "$(echo $((RANDOM % "$ALCANCE + 1")))"
  #(( "INDEX+=1" )) || : é a mesma coisa que let "INDEX+=1", onde : é a mesma coisa que true
done
